name: Sequential Toolbox Builds

on:
  push:
    branches:
      - main
  # Run weekly on Sunday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  # First branch build job
  build-tools:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for ghcr.io push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make tbx-build-tools toolbox image
        run: cd build-tools && make .env && make

  # tbx-runtimes:
  #   needs: tbx-build-tools
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: tbx-runtimes
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Make tbx-runtimes toolbox image
  #       run: make
  #
  # tbx-coding:
  #   needs: tbx-runtimes
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: tbx-coding
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Make tbx-coding toolbox
  #       run: make
