name: tbx runtimes toolbox
on:
  push:
    branches:
    - tbx-runtimes
    paths-ignore:
    - '**/README.md'
jobs:
  build_runtimes_toolbox:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ github.token }}
        - uses: actions/checkout@v4
          with:
            token: ${{ github.token }}
        - name: Make runtimes toolbox image
          run: make
        - name: Commit and push README.md changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Update README.md from Makefile build"  README.md
            # NOTE: push does not trigger action run
            git push
